include : package:flutter_lints/flutter.yaml
analyzer:
  errors:
    invalid_annotation_target: ignore
    always_specify_types: ignore
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.config.dart"

linter:
  rules:
    # Style rules
    always_declare_return_types: true
    always_specify_types: true
    prefer_single_quotes: true
    require_trailing_commas: true

    # Design rules
    avoid_dynamic_calls: true
    avoid_empty_else: true

    # Performance rules
    avoid_unnecessary_containers: true
    sized_box_for_whitespace: true
    use_key_in_widget_constructors: true
